source 'https://rubygems.org'

# Base
gem 'rails', '4.2.1'
gem 'pg'

# Controllers
gem 'responders', '~> 2.0'
gem 'has_scope'
gem 'inherited_resources'

# Server stuffs
group :development do
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano3-unicorn'
  gem 'capistrano-sidekiq'

  gem "letter_opener"
  gem 'meta_request'
  gem "better_errors"
end

gem 'unicorn'

# Assets pipeline
gem "haml"
gem 'uglifier', '>= 1.3.0'

# Auth stuff
gem "devise"
# gem 'omniauth-facebook'
# gem 'omniauth-google'
gem 'omniauth-twitter'


# SCSS

gem 'sass-rails', '~> 5.0'
gem 'bourbon'
gem 'neat'
gem 'bitters'
gem 'refills'

# ES6

gem "sprockets", '~> 3.0'
gem "sprockets-es6"
gem 'react-rails', '~> 1.0'
gem "bower-rails", "~> 0.9.2"


group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

