base: &base
 adapter: postgresql
 encoding: unicode
 pool: 15
 host: localhost
 timeout: 5000
 username: deployer
 password:

development:
 database: %NAME_UNDERSCORE_dev
 <<: *base

test: &test
 database: %NAME_UNDERSCORE_test
 <<: *base

staging:
 database: %NAME_UNDERSCORE_staging
 <<: *base

production:
 database: %NAME_UNDERSCORE_prod
 <<: *base
